export const DEFAULT_LANGUAGE = 'en';
export const LANGUAGES: { [name: string]: string } = {
	en: 'English',
	ar: 'العربية',
	bn: 'বাংলা',
	ca: 'Català',
	cs: 'Čeština',
	da: 'Dansk',
	de: 'Deutsch',
	el: 'Ελληνικά',
	es: 'Español',
	eu: 'Euskara',
	fa: 'فارسی',
	fi: 'Suomi',
	fil: 'Filipino',
	fr: 'Français',
	hi: 'हिन्दी',
	hu: 'Magyar',
	id: 'Bahasa Indonesia',
	it: 'Italiano',
	jp: '日本語',
	ko: '한국어',
	ms: 'Bahasa Melayu',
	nl: 'Nederlands',
	no: 'Norsk',
	pl: 'Polski',
	pt: 'Português',
	ro: 'Română',
	ru: 'русский',
	sv: 'Svenska',
	sw: 'Kiswahili',
	ta: 'தமிழ்',
	te: 'తెలుగు',
	th: 'ไทย',
	tr: 'Türkçe',
	uk: 'Українська',
	ur: 'اردو',
	vi: 'Tiếng Việt',
	zh: '中文'
};
