name: 'app-linux'

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build-tauri:
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf


      - name: Write mah build config
        run: |
          echo "{\"name\": \"Mah\", \"mobile\":true}" > custom-build-config.json


      - name: Install mah dependencies
        run: npm install

      - name: Install tauri dependencies
        run: cd resources/apps && npm install

      - name: Build linux app
        run: |
          cd resources/apps
          npm run linux


      - name: Upload linux artifacts
        uses: actions/upload-artifact@v4
        if: github.ref_type != 'tag'
        with:
          name: 'linux'
          retention-days: 10
          path:  |
            resources/apps/tauri/target/release/bundle/**/*.rpm
            resources/apps/tauri/target/release/bundle/**/*.deb
            resources/apps/tauri/target/release/bundle/**/*.AppImage


      - name: Upload release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            resources/apps/tauri/target/release/bundle/**/*.rpm
            resources/apps/tauri/target/release/bundle/**/*.deb
            resources/apps/tauri/target/release/bundle/**/*.AppImage

