name: ci

permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm install
      - run: npm run test
      - run: npm run build:prod
