name: test

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags-ignore:
      - '**'
    paths-ignore:
      - 'README.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26.x
          package-manager-cache: false

      - run: npm ci

      - run: npm run build:prod

      - run: npm run coverage

      - uses: qltysh/qlty-action/coverage@08a0a862c159eae9b9003081da6663d96efef637 # v2.3.0
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/lcov.info
